dbConnection=dbConnect('mysql','dbname=redfieldroleplay;host=localhost','root','123')

if(dbConnection)then
	outputDebugString('DB-Connection: ✔')
else
	outputDebugString('DB-Connection: ✘')
end
	
function redfieldSaveData()
	if(getElementData(source,'loggedin')==1)then
		dbExec(dbConnection,'UPDATE userdata SET Money=? WHERE Username =?;',getPlayerMoney(source),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Autoschein=? WHERE Username =?;',getElementData(source,'Autoschein'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Motorradschein=? WHERE Username =?;',getElementData(source,'Motorradschein'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Lkwschein=? WHERE Username =?;',getElementData(source,'Lkwschein'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Helikopterschein=? WHERE Username =?;',getElementData(source,'Helikopterschein'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Flugschein=? WHERE Username =?;',getElementData(source,'Flugschein'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Bootschein=? WHERE Username =?;',getElementData(source,'Bootschein'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Personalausweis=? WHERE Username =?;',getElementData(source,'Personalausweis'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Arbeitsgenehmigung=? WHERE Username =?;',getElementData(source,'Arbeitsgenehmigung'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Bankpin=? WHERE Username =?;',getElementData(source,'Bankpin'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Bankmoney=? WHERE Username =?;',getElementData(source,'Bankmoney'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Level=? WHERE Username =?;',getElementData(source,'Level'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Erfahrungspunkte=? WHERE Username =?;',getElementData(source,'Erfahrungspunkte'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Spielzeit=? WHERE Username =?;',getElementData(source,'Spielzeit'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Hunger=? WHERE Username =?;',getElementData(source,'Hunger'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Adminrang=? WHERE Username =?;',getElementData(source,'Adminrang'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Fraktion=? WHERE Username =?;',getElementData(source,'Fraktion'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Fraktionrang=? WHERE Username =?;',getElementData(source,'Fraktionrang'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Mats=? WHERE Username =?;',getElementData(source,'Mats'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Drogen=? WHERE Username =?;',getElementData(source,'Drogen'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Matstransporter=? WHERE Username =?;',getElementData(source,'Matstransporter'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Drogentransporter=? WHERE Username =?;',getElementData(source,'Drogentransporter'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Jobgehalt=? WHERE Username =?;',getElementData(source,'Jobgehalt'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Wanteds=? WHERE Username =?;',getElementData(source,'Wanteds'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Stvo=? WHERE Username =?;',getElementData(source,'Stvo'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Job=? WHERE Username =?;',getElementData(source,'Job'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Flugjobskills=? WHERE Username =?;',getElementData(source,'Flugjobskills'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Knastzeit=? WHERE Username =?;',getElementData(source,'Knastzeit'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Prisontime=? WHERE Username =?;',getElementData(source,'Prisontime'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Skin=? WHERE Username =?;',getElementData(source,'Skin'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Waffenschein=? WHERE Username =?;',getElementData(source,'Waffenschein'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Motel=? WHERE Username =?;',getElementData(source,'Motel'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Mute=? WHERE Username =?;',getElementData(source,'Mute'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Handy=? WHERE Username =?;',getElementData(source,'Handy'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Telefonnummer=? WHERE Username =?;',getElementData(source,'Telefonnummer'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Infobox=? WHERE Username =?;',getElementData(source,'Infobox'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Pizzajobskills=? WHERE Username =?;',getElementData(source,'Pizzajobskills'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Status=? WHERE Username =?;',getElementData(source,'Status'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET SpawnX=? WHERE Username =?;',getElementData(source,'SpawnX'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET SpawnY=? WHERE Username =?;',getElementData(source,'SpawnY'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET SpawnZ=? WHERE Username =?;',getElementData(source,'SpawnZ'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Housekey=? WHERE Username =?;',getElementData(source,'Housekey'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Holzjobskillpunkte=? WHERE Username =?;',getElementData(source,'Holzjobskillpunkte'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Eichenholz=? WHERE Username =?;',getElementData(source,'Eichenholz'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Birkenholz=? WHERE Username =?;',getElementData(source,'Birkenholz'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Interior=? WHERE Username =?;',getElementData(source,'Interior'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchUmgezogen=? WHERE Username =?;',getElementData(source,'AchUmgezogen'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchFahrzeug=? WHERE Username =?;',getElementData(source,'AchFahrzeug'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Ach1Million=? WHERE Username =?;',getElementData(source,'Ach1Million'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchKonto=? WHERE Username =?;',getElementData(source,'AchKonto'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchGestorben=? WHERE Username =?;',getElementData(source,'AchGestorben'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchCarlicence=? WHERE Username =?;',getElementData(source,'AchCarlicence'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchFraktion=? WHERE Username =?;',getElementData(source,'AchFraktion'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchLevel5=? WHERE Username =?;',getElementData(source,'AchLevel5'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchBonusshopbuy=? WHERE Username =?;',getElementData(source,'AchBonusshopbuy'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Ach25TausendEXP=? WHERE Username =?;',getElementData(source,'Ach25TausendEXP'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchMiniMission=? WHERE Username =?;',getElementData(source,'AchMiniMission'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchPayday=? WHERE Username =?;',getElementData(source,'AchPayday'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Ach5Hours=? WHERE Username =?;',getElementData(source,'Ach5Hours'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchHouse=? WHERE Username =?;',getElementData(source,'AchHouse'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchSpawn=? WHERE Username =?;',getElementData(source,'AchSpawn'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET AchHolz=? WHERE Username =?;',getElementData(source,'AchHolz'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET ImHaus=? WHERE Username =?;',getElementData(source,'ImHaus'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Kills=? WHERE Username =?;',getElementData(source,'Kills'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Tode=? WHERE Username =?;',getElementData(source,'Tode'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Gwsgestartet=? WHERE Username =?;',getElementData(source,'Gwsgestartet'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Intro=? WHERE Username =?;',getElementData(source,'Intro'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Tankwartjobskills=? WHERE Username =?;',getElementData(source,'Tankwartjobskills'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Language=? WHERE Username =?;',getElementData(source,'Language'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1704=? WHERE Username =?;',getElementData(source,'Objekt1704'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1705=? WHERE Username =?;',getElementData(source,'Objekt1705'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1708=? WHERE Username =?;',getElementData(source,'Objekt1708'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1711=? WHERE Username =?;',getElementData(source,'Objekt1711'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1720=? WHERE Username =?;',getElementData(source,'Objekt1720'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1723=? WHERE Username =?;',getElementData(source,'Objekt1723'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1726=? WHERE Username =?;',getElementData(source,'Objekt1726'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1727=? WHERE Username =?;',getElementData(source,'Objekt1727'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1728=? WHERE Username =?;',getElementData(source,'Objekt1728'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1729=? WHERE Username =?;',getElementData(source,'Objekt1729'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1739=? WHERE Username =?;',getElementData(source,'Objekt1739'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1825=? WHERE Username =?;',getElementData(source,'Objekt1825'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1896=? WHERE Username =?;',getElementData(source,'Objekt1896'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1998=? WHERE Username =?;',getElementData(source,'Objekt1998'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt2096=? WHERE Username =?;',getElementData(source,'Objekt2096'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt2205=? WHERE Username =?;',getElementData(source,'Objekt2205'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt2313=? WHERE Username =?;',getElementData(source,'Objekt2313'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1518=? WHERE Username =?;',getElementData(source,'Objekt1518'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1752=? WHERE Username =?;',getElementData(source,'Objekt1752'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt1786=? WHERE Username =?;',getElementData(source,'Objekt1786'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt16377=? WHERE Username =?;',getElementData(source,'Objekt16377'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt638=? WHERE Username =?;',getElementData(source,'Objekt638'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt970=? WHERE Username =?;',getElementData(source,'Objekt970'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt17037=? WHERE Username =?;',getElementData(source,'Objekt17037'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Dimension=? WHERE Username =?;',getElementData(source,'Dimension'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt2526=? WHERE Username =?;',getElementData(source,'Objekt2526'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt2514=? WHERE Username =?;',getElementData(source,'Objekt2514'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt2527=? WHERE Username =?;',getElementData(source,'Objekt2527'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Objekt2524=? WHERE Username =?;',getElementData(source,'Objekt2524'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Geldtransporter=? WHERE Username =?;',getElementData(source,'Geldtransporter'),getPlayerName(source))
		dbExec(dbConnection,'UPDATE userdata SET Versicherung=? WHERE Username =?;',getElementData(source,'Versicherung'),getPlayerName(source))
	end
end
addEventHandler('onPlayerQuit',root,redfieldSaveData)